#!/usr/bin/env python3
"""Generated by build-plugins.py. Exports the plugin's workspace root (and, when
provided, the operator data root) for the rest of the session's Bash calls.

WORKSPACE_ROOT is the first-honored override in scripts/utils/paths.py, so this
is what makes bundled scripts resolve their root from ~/.claude/plugins/cache
instead of marker-walking (the cache has no CLAUDE.md/.claude markers of the
real workspace). HEADING_OS_DATA is exported only when the operator supplied a
data path via plugin userConfig; otherwise the data root falls back to demo.
"""
import os

env_file = os.environ.get("CLAUDE_ENV_FILE")
plugin_root = os.environ.get("CLAUDE_PLUGIN_ROOT", "")
if env_file and plugin_root:
    lines = [f'export WORKSPACE_ROOT="{plugin_root}"\n']
    data_root = os.environ.get("CLAUDE_PLUGIN_OPTION_DATA_ROOT")
    if data_root:
        lines.append(f'export HEADING_OS_DATA="{data_root}"\n')
    with open(env_file, "a", encoding="utf-8") as f:
        f.writelines(lines)
